export type Doctor = { id: string; name: string; specialty: string };
export type Clinic = { id: string; name: string; address: string; phone: string; timezone: string; opens: string; closes: string; doctors: Doctor[] };
export type Patient = { id: string; clinicId: string; name: string; phone: string; consent: boolean };
export type Appointment = { id: string; clinicId: string; patientId: string; doctorId: string; date: string; time: string; duration: number; reason: string; status: 'scheduled'|'completed'|'cancelled' };
export type Reminder = { id: string; clinicId: string; patientId: string; date: string; time: string; message: string; status: 'scheduled'|'simulated-sent'|'cancelled'; sentAt?: string; sentMessage?: string };
export type Database = { version: 1; activeClinicId: string; clinics: Clinic[]; patients: Patient[]; appointments: Appointment[]; reminders: Reminder[] };
export function zonedNow(timezone: string, now = new Date()) { const parts = new Intl.DateTimeFormat('en-CA',{timeZone:timezone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(now); const get=(t:string)=>parts.find(p=>p.type===t)!.value; return {date:`${get('year')}-${get('month')}-${get('day')}`,time:`${get('hour')}:${get('minute')}`}; }
export const today = (timezone='Asia/Kolkata') => zonedNow(timezone).date;
export const addDays=(date:string,n:number)=>{const d=new Date(date+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)};
export const dateLabel=(date:string,opts:Intl.DateTimeFormatOptions={day:'numeric',month:'long',year:'numeric'})=>new Intl.DateTimeFormat('en-IN',{...opts,timeZone:'UTC'}).format(new Date(date+'T12:00:00Z'));
export const minutes=(t:string)=>Number(t.split(':')[0])*60+Number(t.split(':')[1]);
export const clockLabel=(t:string)=>`${Number(t.slice(0,2))%12||12}:${t.slice(3)} ${Number(t.slice(0,2))>=12?'PM':'AM'}`;
export const initials=(name:string)=>name.replace(/^Dr\.\s*/,'').split(' ').filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase();
export function normalizePhone(value:string){let p=value.replace(/[\s()-]/g,'');if(/^\d{10}$/.test(p))p='+91'+p;if(!/^\+[1-9]\d{7,14}$/.test(p))throw new Error('Enter a valid phone number with country code, such as +91 98765 43210.');return p;}
export function validateClinic(c:Clinic){if(!c.name.trim()||!c.address.trim())throw new Error('Enter the clinic name and address.');normalizePhone(c.phone);try{today(c.timezone)}catch{throw new Error('Choose a valid timezone.')};if(!/^\d{2}:\d{2}$/.test(c.opens)||!/^\d{2}:\d{2}$/.test(c.closes)||minutes(c.opens)>=minutes(c.closes))throw new Error('Closing time must be after opening time.');if(!c.doctors.length||c.doctors.some(d=>!d.name.trim()))throw new Error('Add at least one doctor with a name.');}
export function validateAppointment(db:Database,a:Appointment){const c=db.clinics.find(c=>c.id===a.clinicId);if(!c||!db.patients.some(p=>p.id===a.patientId&&p.clinicId===c.id)||!c.doctors.some(d=>d.id===a.doctorId))throw new Error('Choose a patient and doctor from this clinic.');if(!/^\d{4}-\d{2}-\d{2}$/.test(a.date)||!/^([01]\d|2[0-3]):[0-5]\d$/.test(a.time)||!Number.isInteger(a.duration)||a.duration<5||a.duration>240)throw new Error('Enter a valid date, time, and duration from 5 to 240 minutes.');const start=minutes(a.time),end=start+a.duration;if(start<minutes(c.opens)||end>minutes(c.closes))throw new Error(`Appointments must fit within clinic hours: ${clockLabel(c.opens)}–${clockLabel(c.closes)}.`);if(a.status!=='cancelled'&&db.appointments.some(b=>b.id!==a.id&&b.clinicId===a.clinicId&&b.doctorId===a.doctorId&&b.date===a.date&&b.status!=='cancelled'&&start<minutes(b.time)+b.duration&&end>minutes(b.time)))throw new Error('This doctor already has an appointment at that time. Choose another slot.');}
export function validateReminder(db:Database,r:Reminder){const p=db.patients.find(p=>p.id===r.patientId&&p.clinicId===r.clinicId);if(!p)throw new Error('Choose a patient from this clinic.');if(!p.consent)throw new Error('WhatsApp consent is required. Update the patient’s consent before continuing.');if(!r.message.trim())throw new Error('Enter a reminder message.');if(!/^\d{4}-\d{2}-\d{2}$/.test(r.date)||!/^([01]\d|2[0-3]):[0-5]\d$/.test(r.time))throw new Error('Choose a valid reminder date and time.');}
export function reminderMessage(c:Clinic,r:Reminder){return `${r.message.trim()}\n\n${c.name}\nFor appointments or questions: ${c.phone}`;}
export function reminderStatus(r:Reminder,c:Clinic,now=new Date()){const z=zonedNow(c.timezone,now);return r.status==='scheduled'&&`${r.date}T${r.time}`<=`${z.date}T${z.time}`?'due':r.status;}
export interface MessagingService { simulate(db:Database,r:Reminder):Reminder; }
export const messaging:MessagingService={simulate(db,r){validateReminder(db,r);if(r.status!=='scheduled')throw new Error('Only scheduled reminders can be simulated.');const c=db.clinics.find(c=>c.id===r.clinicId)!;return {...r,status:'simulated-sent',sentAt:new Date().toISOString(),sentMessage:reminderMessage(c,r)};}};
export function seed():Database {const date=today();const clinics:Clinic[]=[{id:'greenleaf',name:'Greenleaf Clinic',address:'Indiranagar, Bengaluru',phone:'+918000000001',timezone:'Asia/Kolkata',opens:'09:00',closes:'19:00',doctors:[{id:'priya',name:'Dr. Priya Nair',specialty:'General Physician'},{id:'arjun',name:'Dr. Arjun Mehta',specialty:'Pediatrician'}]},{id:'lakeside',name:'Lakeside Medical Centre',address:'Whitefield, Bengaluru',phone:'+918000000002',timezone:'Asia/Kolkata',opens:'08:00',closes:'18:00',doctors:[{id:'neha',name:'Dr. Neha Shah',specialty:'General Physician'}]}];const names=['Aarav Sharma','Meera Iyer','Rohan Patel','Ananya Rao','Vikram Desai','Diya Kapoor','Kabir Singh','Ishita Menon'];const patients=names.map((name,i)=>({id:'p'+i,clinicId:'greenleaf',name,phone:'+9180000001'+String(i).padStart(2,'0'),consent:i!==6}));patients.push({id:'lake-p',clinicId:'lakeside',name:'Sana Verma',phone:'+918000000200',consent:true});const appointments:Appointment[]=names.map((_,i)=>({id:'a'+i,clinicId:'greenleaf',patientId:'p'+i,doctorId:i%3===2?'arjun':'priya',date,time:['09:00','09:30','10:00','10:30','11:15','14:00','15:30','16:00'][i],duration:30,reason:i%3===2?'Pediatric consultation':i%2?'Follow-up visit':'General consultation',status:i<2?'completed':'scheduled'}));for(let i=1;i<8;i++)appointments.push({id:'future'+i,clinicId:'greenleaf',patientId:'p'+i,doctorId:'priya',date:addDays(date,i),time:i%2?'10:00':'14:30',duration:30,reason:'Follow-up visit',status:'scheduled'});return {version:1,activeClinicId:'greenleaf',clinics,patients,appointments,reminders:[0,1,2,3].map(i=>({id:'r'+i,clinicId:'greenleaf',patientId:'p'+i,date:i<3?addDays(date,-1):addDays(date,1),time:'09:00',message:`Hello ${names[i].split(' ')[0]}, this is a friendly reminder to schedule your follow-up visit. Please call us to find a time that works for you.`,status:'scheduled'}))};}
export interface DataRepository{load():Database;save(db:Database):void;}
export const repository:DataRepository={load(){const raw=localStorage.getItem('clinicloop-demo-v1');if(!raw)return seed();const db=JSON.parse(raw);if(db.version!==1||!Array.isArray(db.clinics)||!db.clinics.length||!Array.isArray(db.patients)||!Array.isArray(db.appointments)||!Array.isArray(db.reminders)||!db.clinics.some((c:Clinic)=>c.id===db.activeClinicId))throw new Error('Saved demo data could not be loaded. Reset the demo in Clinic settings to start again.');return db as Database;},save(db){localStorage.setItem('clinicloop-demo-v1',JSON.stringify(db));}};
